create table measurement(
    measurement_id int primary key generated by default as identity,
    temperature_value numeric(4,2) check ( temperature_value > -100 ) check ( temperature_value < 100 ) not null,
    location_of_measurement varchar,
    time_of_measurement date not null,
    raining boolean not null,
    wind_speed numeric(5,2) check ( wind_speed < 140 ) check ( wind_speed > 0 ) not null,
    sensor_id int references sensor(sensor_id) on delete set null
);